### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by ronoppenheimer**
I updated the file, let me know if it is missing anything or you want me to make some changes.

### CODE REVIEW

**Comment by mattlag** [comment]
I'll make some slight changes, but those are some great additions.  Thanks!

**Comment by ronoppenheimer** [comment]
Awesome! Thanks so much for letting me contribute!

**Comment by mattlag** [comment]
No problem.  Are you a font designer, or developer, or a little bit of both?  I'm trying to get to a point where it's easier to contribute from a code perspective... components is kind of causing me to re-write and re-factor a lot of the code, so hopefully after v1 shipps it will be easier.

**Comment by ronoppenheimer** [comment]
I'm actually a Junior at Lick-Wilmerding High School. I'm in my school's Advanced Computing class and we had an assignment to find an Open Source Project we are interested, and contribute to it. I'd love to keep contributing though even though we've just about finished the assignment.

**Comment by davelab6** [comment]
Wow Ron, that's awesome :) I wish I was a kid in school again, when I was
(in the late 90s) it was so hard to get access to libre software :)

**Pull request merged**
